--------------------------------------------------------------------------------
-- 02_book_jobs_table.sql
-- The Book_Jobs metadata table (same layout as the Excel sheet) and an
-- XLSX loader that uses APEX_DATA_PARSER when APEX is installed.
--
-- Loading options
--   a) @data/output/book_jobs_load.sql      (generated by python/lineage_engine.py)
--   b) exec load_book_jobs_xlsx(:blob)      (APEX_DATA_PARSER, e.g. from an APEX file browse item)
--   c) SQL Developer / SQLcl "load" of the sheet saved as CSV
--------------------------------------------------------------------------------
set define off

begin
  execute immediate 'drop table book_jobs purge';
exception when others then if sqlcode != -942 then raise; end if;
end;
/

create table book_jobs (
  job_num        number         not null,
  job_names      varchar2(4000),
  target_object  varchar2(4000),
  source_object  varchar2(4000),
  unique_col     varchar2(4000),
  filter_clause  varchar2(4000),
  sql_stmt       clob,
  disabled_flag  varchar2(30),
  constraint book_jobs_pk primary key (job_num)
);

--------------------------------------------------------------------------------
-- Load an uploaded .xlsx (first sheet, header row expected) into BOOK_JOBS.
-- Dynamic SQL keeps this procedure valid in databases without APEX.
--------------------------------------------------------------------------------
create or replace procedure load_book_jobs_xlsx (
  p_xlsx      in blob,
  p_truncate  in boolean default true
) as
  l_rows number;
begin
  if p_truncate then
    execute immediate 'truncate table book_jobs';
  end if;

  execute immediate q'[
    insert into book_jobs (job_num, job_names, target_object, source_object,
                           unique_col, filter_clause, sql_stmt, disabled_flag)
    select to_number(col001), col002, col003, col004, col005, col006,
           replace(col007, '_x000D_'), col008
    from   table(apex_data_parser.parse(
                   p_content         => :b,
                   p_file_name       => 'book_jobs.xlsx',
                   p_skip_rows       => 1,
                   p_max_rows        => 100000))
    where  col001 is not null]'
  using p_xlsx;
  l_rows := sql%rowcount;
  dbms_output.put_line(l_rows || ' Book_Jobs rows loaded.');
end load_book_jobs_xlsx;
/
