--------------------------------------------------------------------------------
-- 05_view_extraction.sql
-- Queries to pull the definitions of every view discovered in the lineage.
--
-- LIN_ENGINE.RUN already captures view text automatically into LIN_VIEW_DDL;
-- these queries are for ad-hoc use, exports and other databases.
-- A version with the literal list of view names discovered from the Excel
-- sheet is generated by the Python engine: data/output/extract_view_ddl.sql
--------------------------------------------------------------------------------
set define off
set long 2000000 longchunksize 32767 linesize 32767 pagesize 50000 trimspool on

--------------------------------------------------------------------------------
-- A. Views in the latest lineage run (nodes typed VIEW) and whether they exist
--------------------------------------------------------------------------------
select n.node_name,
       n.node_class,
       n.dag_level,
       case when v.view_name is not null then 'Y' else 'N' end exists_in_db,
       v.text_length
from   lin_v_nodes n
left   join all_views v
       on  v.owner = case when instr(n.node_name, '.') > 0
                          then substr(n.node_name, 1, instr(n.node_name, '.') - 1)
                          else sys_context('USERENV', 'CURRENT_SCHEMA') end
       and v.view_name = case when instr(n.node_name, '.') > 0
                              then substr(n.node_name, instr(n.node_name, '.') + 1)
                              else n.node_name end
where  n.node_type = 'VIEW'
order  by n.dag_level, n.node_name;

--------------------------------------------------------------------------------
-- B. Oracle dictionary: ALL_VIEWS / USER_VIEWS
--    TEXT is a LONG column; TEXT_VC (12c+) is the first 4000 characters.
--------------------------------------------------------------------------------
select v.owner, v.view_name, v.text_length, v.text_vc
from   all_views v
join   lin_v_nodes n on n.node_name = v.view_name
where  v.owner = sys_context('USERENV', 'CURRENT_SCHEMA')
order  by v.view_name;

-- USER_VIEWS variant (current schema only, no privileges needed)
select view_name, text_length, text_vc
from   user_views
where  view_name in (select node_name from lin_v_nodes where node_type = 'VIEW')
order  by view_name;

--------------------------------------------------------------------------------
-- C. Full text as CLOB: LONG -> CLOB conversion with TO_LOB (INSERT ... SELECT only)
--    (this is what LIN_ENGINE does internally)
--------------------------------------------------------------------------------
-- create global temporary table lin_tmp_view_text (owner varchar2(128), view_name varchar2(128), view_text clob)
--   on commit preserve rows;
-- insert into lin_tmp_view_text
-- select owner, view_name, to_lob(text)
-- from   all_views
-- where  owner = sys_context('USERENV', 'CURRENT_SCHEMA')
-- and    view_name in (select node_name from lin_v_nodes where node_type = 'VIEW');

select owner, view_name, text_length, view_text
from   lin_view_ddl
where  run_id = (select run_id from lin_v_latest_run)
order  by capture_level, view_name;

--------------------------------------------------------------------------------
-- D. Complete CREATE VIEW DDL with DBMS_METADATA (column list, FORCE, etc.)
--------------------------------------------------------------------------------
begin
  dbms_metadata.set_transform_param(dbms_metadata.session_transform, 'SQLTERMINATOR', true);
  dbms_metadata.set_transform_param(dbms_metadata.session_transform, 'PRETTY', true);
end;
/
select v.view_name,
       dbms_metadata.get_ddl('VIEW', v.view_name, v.owner) ddl
from   all_views v
where  v.owner = sys_context('USERENV', 'CURRENT_SCHEMA')
and    v.view_name in (select node_name from lin_v_nodes where node_type = 'VIEW')
order  by v.view_name;

-- one view:  select lin_engine.view_ddl('APP_SNAP_BKG_V') from dual;

--------------------------------------------------------------------------------
-- E. View dependency tree from the dictionary (ALL_DEPENDENCIES), all levels
--------------------------------------------------------------------------------
select lpad(' ', 2 * (level - 1)) || d.referenced_name || ' (' || d.referenced_type || ')' dependency_tree,
       level depth,
       d.name parent_view
from   all_dependencies d
where  d.referenced_owner not in ('SYS', 'PUBLIC')
start  with d.owner = sys_context('USERENV', 'CURRENT_SCHEMA')
       and d.type = 'VIEW'
       and d.name in (select node_name from lin_v_nodes where node_type = 'VIEW' and dag_level is not null)
connect by nocycle prior d.referenced_name  = d.name
           and prior d.referenced_owner = d.owner
           and prior d.referenced_type  = 'VIEW';

--------------------------------------------------------------------------------
-- F. Columns of every view in the lineage (ALL_TAB_COLUMNS)
--------------------------------------------------------------------------------
select c.table_name view_name, c.column_id, c.column_name, c.data_type, c.data_length,
       c.data_precision, c.data_scale, c.nullable
from   all_tab_columns c
where  c.owner = sys_context('USERENV', 'CURRENT_SCHEMA')
and    c.table_name in (select node_name from lin_v_nodes where node_type = 'VIEW')
order  by c.table_name, c.column_id;

--------------------------------------------------------------------------------
-- G. ANSI INFORMATION_SCHEMA equivalents (PostgreSQL, SQL Server, MySQL,
--    Snowflake, BigQuery ...) - run on the respective platform
--------------------------------------------------------------------------------
-- select table_schema, table_name, view_definition
-- from   information_schema.views
-- where  table_name in (/* list from data/output/nodes.csv where NODE_TYPE = 'VIEW' */);
--
-- select view_schema, view_name, table_schema, table_name      -- view -> table usage
-- from   information_schema.view_table_usage;
--
-- select table_schema, table_name, column_name, ordinal_position, data_type
-- from   information_schema.columns
-- where  table_name in (/* ... */)
-- order  by table_name, ordinal_position;
